name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: 
        - cd HW07
        - npm install

      
    - name: Check formatting
      run: 
      - cd HW07
      - npm run format:check
      
    - name: Run linters
      run: 
      - cd HW07
      - npm run lint
      
    - name: Run tests
      run: 
      - cd HW07
      - npm test
      
    - name: Run tests with coverage
      run: 
      - cd HW07
      - npm run test:coverage